package io.nekohasekai.sfa.compose.screen.tools

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material.icons.filled.KeyboardArrowDown
import androidx.compose.material.icons.filled.KeyboardArrowUp
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Scaffold
import androidx.compose.material3.SnackbarHost
import androidx.compose.material3.SnackbarHostState
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.navigation.NavController
import kotlinx.coroutines.launch
import org.json.JSONArray
import org.json.JSONObject

/**
 * Fool-proof Chain outbound builder.
 * User picks hop tags in order; app generates valid chain JSON to paste into profile.
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ChainBuilderScreen(navController: NavController) {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()
    val snackbar = remember { SnackbarHostState() }

    var chainTag by remember { mutableStateOf("my-chain") }
    var hopInput by remember { mutableStateOf("") }
    val hops = remember { mutableStateListOf<String>() }
    var generated by remember { mutableStateOf("") }

    fun buildJson(): String {
        val outbound = JSONObject()
        outbound.put("type", "chain")
        outbound.put("tag", chainTag.trim().ifEmpty { "my-chain" })
        val arr = JSONArray()
        hops.forEach { arr.put(it) }
        outbound.put("outbounds", arr)
        return outbound.toString(2)
    }

    fun regenerate() {
        generated = if (hops.size >= 2 && chainTag.isNotBlank()) buildJson() else ""
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("链式代理生成器") },
                navigationIcon = {
                    IconButton(onClick = { navController.navigateUp() }) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "返回")
                    }
                },
            )
        },
        snackbarHost = { SnackbarHost(snackbar) },
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .padding(16.dp)
                .verticalScroll(rememberScrollState()),
            verticalArrangement = Arrangement.spacedBy(12.dp),
        ) {
            Text(
                text = "按顺序添加节点（至少 2 个），自动生成 chain 配置。无需手写 JSON。",
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
            )

            OutlinedTextField(
                value = chainTag,
                onValueChange = {
                    chainTag = it
                    regenerate()
                },
                label = { Text("链条名称 (tag)") },
                singleLine = true,
                modifier = Modifier.fillMaxWidth(),
            )

            Text("节点顺序（从上到下 = 第一跳 → 出口）", style = MaterialTheme.typography.titleSmall)

            if (hops.isEmpty()) {
                Text(
                    "还没有添加节点。请输入已有 outbound 的 tag，例如 proxy-a",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
            }

            hops.forEachIndexed { index, tag ->
                Card(
                    colors = CardDefaults.cardColors(
                        containerColor = MaterialTheme.colorScheme.surfaceContainer,
                    ),
                    shape = RoundedCornerShape(12.dp),
                    modifier = Modifier.fillMaxWidth(),
                ) {
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(horizontal = 8.dp, vertical = 4.dp),
                    ) {
                        Text(
                            text = "${index + 1}",
                            style = MaterialTheme.typography.titleMedium,
                            modifier = Modifier.width(28.dp),
                        )
                        Text(
                            text = tag,
                            style = MaterialTheme.typography.bodyLarge,
                            modifier = Modifier.weight(1f),
                        )
                        IconButton(
                            onClick = {
                                if (index > 0) {
                                    val item = hops.removeAt(index)
                                    hops.add(index - 1, item)
                                    regenerate()
                                }
                            },
                            enabled = index > 0,
                        ) {
                            Icon(Icons.Default.KeyboardArrowUp, contentDescription = "上移")
                        }
                        IconButton(
                            onClick = {
                                if (index < hops.lastIndex) {
                                    val item = hops.removeAt(index)
                                    hops.add(index + 1, item)
                                    regenerate()
                                }
                            },
                            enabled = index < hops.lastIndex,
                        ) {
                            Icon(Icons.Default.KeyboardArrowDown, contentDescription = "下移")
                        }
                        IconButton(
                            onClick = {
                                hops.removeAt(index)
                                regenerate()
                            },
                        ) {
                            Icon(Icons.Default.Delete, contentDescription = "删除")
                        }
                    }
                }
            }

            Row(
                verticalAlignment = Alignment.CenterVertically,
                modifier = Modifier.fillMaxWidth(),
            ) {
                OutlinedTextField(
                    value = hopInput,
                    onValueChange = { hopInput = it },
                    label = { Text("节点 tag") },
                    singleLine = true,
                    modifier = Modifier.weight(1f),
                )
                Spacer(Modifier = Modifier.width(8.dp))
                Button(
                    onClick = {
                        val tag = hopInput.trim()
                        if (tag.isEmpty()) {
                            scope.launch { snackbar.showSnackbar("请输入节点 tag") }
                            return@Button
                        }
                        if (hops.contains(tag)) {
                            scope.launch { snackbar.showSnackbar("节点已在列表中") }
                            return@Button
                        }
                        hops.add(tag)
                        hopInput = ""
                        regenerate()
                    },
                ) {
                    Icon(Icons.Default.Add, contentDescription = null)
                    Spacer(modifier = Modifier.width(4.dp))
                    Text("添加")
                }
            }

            Button(
                onClick = {
                    if (hops.size < 2) {
                        scope.launch { snackbar.showSnackbar("至少需要 2 个节点") }
                        return@Button
                    }
                    if (chainTag.isBlank()) {
                        scope.launch { snackbar.showSnackbar("请填写链条名称") }
                        return@Button
                    }
                    generated = buildJson()
                    scope.launch { snackbar.showSnackbar("已生成配置") }
                },
                modifier = Modifier.fillMaxWidth(),
                enabled = hops.size >= 2 && chainTag.isNotBlank(),
            ) {
                Text("生成 Chain 配置")
            }

            if (generated.isNotEmpty()) {
                Text("生成结果（复制到配置的 outbounds 数组中）", style = MaterialTheme.typography.titleSmall)
                Card(
                    colors = CardDefaults.cardColors(
                        containerColor = MaterialTheme.colorScheme.surfaceContainerHighest,
                    ),
                    modifier = Modifier.fillMaxWidth(),
                ) {
                    Column(modifier = Modifier.padding(12.dp)) {
                        Text(
                            text = generated,
                            style = MaterialTheme.typography.bodySmall,
                            fontFamily = androidx.compose.ui.text.font.FontFamily.Monospace,
                        )
                        Spacer(modifier = Modifier.height(8.dp))
                        Button(
                            onClick = {
                                val cm = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
                                cm.setPrimaryClip(ClipData.newPlainText("chain-json", generated))
                                scope.launch { snackbar.showSnackbar("已复制到剪贴板") }
                            },
                            modifier = Modifier.fillMaxWidth(),
                        ) {
                            Icon(Icons.Default.ContentCopy, contentDescription = null)
                            Spacer(modifier = Modifier.width(8.dp))
                            Text("复制 JSON")
                        }
                    }
                }

                Text(
                    text = "使用方法：打开配置编辑 → 在 outbounds 里粘贴这段 JSON → 路由 final 或规则指向 \"${chainTag.ifBlank { "my-chain" }}\"",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
            }
        }
    }
}
